function getGreeting(hour) {
  var greetingsLanguage = {
    ab: { meta: { name: "Abkhaz", nativeName: "аҧсуа" } },
    aa: { meta: { name: "Afar", nativeName: "Afaraf" } },
    af: {
      meta: { name: "Afrikaans", nativeName: "Afrikaans" },
      morning: "Goeie more!",
      afternoon: "Goeie middag!",
      evening: "Goeienaand!",
      night: "Goeie nag!",
    },
    ak: { meta: { name: "Akan", nativeName: "Akan" } },
    sq: {
      meta: { name: "Albanian", nativeName: "Shqip" },
      morning: "Miremengjes!",
      afternoon: "Mirembrema!",
      evening: "Mirembrema!",
      night: "Naten e mire!",
      default: "Përshëndetje!",
    },
    am: {
      meta: { name: "Amharic", nativeName: "አማርኛ" },
      morning: "እንደምን አደርክ!",
      afternoon: "እንደምን ዋልክ!",
      evening: "እንደምን አመሸህ!",
      night: "መልካም ሌሊት!",
      default: "ሰላም!",
    },
    ar: {
      meta: { name: "Arabic", nativeName: "العربية" },
      morning: "صباح الخير!",
      afternoon: "مساء الخير!",
      evening: "مساء الخير!",
      night: "تصبح على خير!",
      default: "مرحبا!",
    },
    an: { meta: { name: "Aragonese", nativeName: "Aragonés" } },
    hy: {
      meta: { name: "Armenian", nativeName: "Հայերեն" },
      morning: "Բարի առավոտ!",
      afternoon: "Բարի օր!",
      evening: "Բարի երեկո!",
      night: "Բարի գիշեր!",
      default: "Բարեւ Ձեզ!",
    },
    as: { meta: { name: "Assamese", nativeName: "অসমীয়া" } },
    av: {
      meta: { name: "Avaric", nativeName: "авар мацӀ, магӀарул мацӀ" },
    },
    ae: { meta: { name: "Avestan", nativeName: "avesta" } },
    ay: { meta: { name: "Aymara", nativeName: "aymar aru" } },
    az: {
      meta: { name: "Azerbaijani", nativeName: "azərbaycan dili" },
      morning: "Sabahınız xeyir!",
      afternoon: "Günortanız Xeyir!",
      evening: "Axşamınız xeyir!",
      night: "Gecəniz xeyir!",
      default: "Salam!",
    },
    bm: { meta: { name: "Bambara", nativeName: "bamanankan" } },
    ba: { meta: { name: "Bashkir", nativeName: "башҡорт теле" } },
    eu: {
      meta: { name: "Basque", nativeName: "euskara, euskera" },
      morning: "Egun on!",
      afternoon: "Arratsalde on!",
      evening: "Arratsalde on!",
      night: "Egun on!",
    },
    be: {
      meta: { name: "Belarusian", nativeName: "Беларуская" },
      morning: "Добрай раніцы!",
      afternoon: "Добры дзень!",
      evening: "Добры вечар!",
      night: "Дабранач!",
      default: "Добры дзень!",
    },
    bn: {
      meta: { name: "Bengali", nativeName: "বাংলা" },
      morning: "সুপ্রভাত!",
      afternoon: "শুভ অপরাহ্ন!",
      evening: "শুভ সন্ধ্যা!",
      night: "শুভ রাত্রি!",
      default: "হ্যালো!",
    },
    bh: { meta: { name: "Bihari", nativeName: "भोजपुरी" } },
    bi: { meta: { name: "Bislama", nativeName: "Bislama" } },
    bs: {
      meta: { name: "Bosnian", nativeName: "bosanski jezik" },
      morning: "Dobro jutro!",
      afternoon: "Dobar dan!",
      evening: "Dobro veče!",
      night: "Laku noc!",
      default: "Zdravo!",
    },
    br: { meta: { name: "Breton", nativeName: "brezhoneg" } },
    bg: {
      meta: { name: "Bulgarian", nativeName: "български език" },
      morning: "Добро утро!",
      afternoon: "Добър ден!",
      evening: "Добър вечер!",
      night: "Лека нощ!",
      default: "Здравейте!",
    },
    my: {
      meta: { name: "Burmese", nativeName: "ဗမာစာ" },
      morning: "မင်္ဂလာနံနက်ခင်းပါ!",
      afternoon: "မင်္ဂလာနေ့လည်ခင်း!",
      evening: "မင်္ဂလာညနေခင်းပါ!",
      night: "ကောင်းသောညပါ!",
      default: "ဟယ်လို!",
    },
    ca: {
      meta: { name: "Catalan; Valencian", nativeName: "Català" },
      morning: "Bon dia!",
      afternoon: "Bona tarda!",
      evening: "Bona nit!",
      night: "Bona nit!",
      default: "Hola!",
    },
    ch: { meta: { name: "Chamorro", nativeName: "Chamoru" } },
    ce: { meta: { name: "Chechen", nativeName: "нохчийн мотт" } },
    ny: {
      meta: {
        name: "Chichewa; Chewa; Nyanja",
        nativeName: "chiCheŵa, chinyanja",
      },
      morning: "M'mawa wabwino!",
      afternoon: "Masana abwino!",
      evening: "Madzulo abwino!",
      night: "Usiku wabwino!",
      default: "Moni!",
    },
    zh: {
      meta: { name: "Chinese", nativeName: "中文 (Zhōngwén), 汉语, 漢語" },
      morning: "早上好!",
      afternoon: "下午好!",
      evening: "晚上好!",
      night: "晚安!",
      default: "你好!",
    },
    cv: { meta: { name: "Chuvash", nativeName: "чӑваш чӗлхи" } },
    kw: { meta: { name: "Cornish", nativeName: "Kernewek" } },
    co: {
      meta: { name: "Corsican", nativeName: "corsu, lingua corsa" },
      morning: "Bonghjornu!",
      afternoon: "Bonu dopu meziornu!",
      evening: "Bona sera!",
      night: "Bona notte!",
      default: "Bonghjornu!",
    },
    cr: { meta: { name: "Cree", nativeName: "ᓀᐦᐃᔭᐍᐏᐣ" } },
    hr: {
      meta: { name: "Croatian", nativeName: "hrvatski" },
      morning: "Dobro jutro!",
      afternoon: "Dobar dan!",
      evening: "Dobra večer!",
      night: "Laku noć!",
      default: "Zdravo!",
    },
    cs: {
      meta: { name: "Czech", nativeName: "česky, čeština" },
      morning: "Dobré ráno!",
      afternoon: "Dobré odpoledne!",
      evening: "Dobrý večer!",
      night: "Dobrou noc!",
      default: "Ahoj!",
    },
    da: {
      meta: { name: "Danish", nativeName: "dansk" },
      morning: "God morgen!",
      afternoon: "God eftermiddag!",
      evening: "God aften!",
      night: "Godnat!",
      default: "Hej!",
    },
    dv: {
      meta: { name: "Divehi; Dhivehi; Maldivian;", nativeName: "ދިވެހި" },
    },
    nl: {
      meta: { name: "Dutch", nativeName: "Nederlands, Vlaams" },
      morning: "Goedemorgen!",
      afternoon: "Goedenmiddag!",
      evening: "Goedenavond!",
      night: "Welterusten!",
      default: "Hallo!",
    },
    en: {
      meta: { name: "English", nativeName: "English" },
      morning: "Good morning!",
      afternoon: "Good afternoon!",
      evening: "Good evening!",
      night: "Good night!",
      default: "Hello!",
    },
    eo: {
      meta: { name: "Esperanto", nativeName: "Esperanto" },
      morning: "Bonan matenon!",
      afternoon: "Bonan posttagmezon!",
      evening: "Bonan vesperon!",
      night: "Bonan nokton!",
      default: "Saluton!",
    },
    et: {
      meta: { name: "Estonian", nativeName: "eesti, eesti keel" },
      morning: "Tere hommikust!",
      afternoon: "Tere päevast!",
      evening: "Tere õhtust!",
      night: "Head ööd!",
      default: "Tere!",
    },
    ee: {
      meta: { name: "Ewe", nativeName: "Eʋegbe" },
      morning: "Tere hommikust!",
      afternoon: "Tere päevast!",
      evening: "Tere õhtust!",
      night: "Head ööd!",
      default: "Tere!",
    },
    fo: { meta: { name: "Faroese", nativeName: "føroyskt" } },
    fj: { meta: { name: "Fijian", nativeName: "vosa Vakaviti" } },
    fi: {
      meta: { name: "Finnish", nativeName: "suomi, suomen kieli" },
      morning: "Hyvää huomenta!",
      afternoon: "Hyvää iltapäivää!",
      evening: "Hyvää iltaa!",
      night: "Hyvää yötä!",
      default: "Hei!",
    },
    fr: {
      meta: { name: "French", nativeName: "français, langue française" },
      morning: "Bonjour!",
      afternoon: "Bonne après-midi!",
      evening: "Bonsoir!",
      night: "Bonne nuit!",
      default: "salut!",
    },
    ff: {
      meta: {
        name: "Fula; Fulah; Pulaar; Pular",
        nativeName: "Fulfulde, Pulaar, Pular",
      },
    },
    gl: {
      meta: { name: "Galician", nativeName: "Galego" },
      morning: "Bos días!",
      afternoon: "Boas tardes!",
      evening: "Boas tardes!",
      night: "Boas noites!",
      default: "Ola!",
    },
    ka: {
      meta: { name: "Georgian", nativeName: "ქართული" },
      morning: "Დილა მშვიდობისა!",
      afternoon: "Შუაღდე მშვიდობისა!",
      evening: "Საღამო მშვიდობისა!",
      night: "Ღამე მშვიდობისა!",
      default: "გამარჯობა!",
    },
    de: {
      meta: { name: "German", nativeName: "Deutsch" },
      morning: "Guten Morgen!",
      afternoon: "Guten Tag!",
      evening: "Guten Abend!",
      night: "Gute Nacht!",
      default: "Hallo!",
    },
    el: {
      meta: { name: "Greek, Modern", nativeName: "Ελληνικά" },
      morning: "Καλημέρα!",
      afternoon: "Καλό απόγευμα!",
      evening: "Καλό απόγευμα!",
      night: "Καληνυχτα!",
      default: "Γειά σου!",
    },
    gn: { meta: { name: "Guaraní", nativeName: "Avañeẽ" } },
    gu: {
      meta: { name: "Gujarati", nativeName: "ગુજરાતી" },
      morning: "સુપ્રભાત!",
      afternoon: "શુભ બપોર!",
      evening: "શુભ સાંજ!",
      night: "શુભ રાત્રી!",
      default: "નમસ્તે!",
    },
    ht: {
      meta: {
        name: "Haitian; Haitian Creole",
        nativeName: "Kreyòl ayisyen",
      },
      morning: "Bonjou!",
      afternoon: "Bon apremidi!",
      evening: "Bonswa!",
      night: "Bòn nwi!",
      default: "Bonjou!",
    },
    ha: {
      meta: { name: "Hausa", nativeName: "Hausa, هَوُسَ" },
      morning: "Ina kwana!",
      afternoon: "Ina kwana!",
      evening: "Barka da yamma!",
      night: "Barka da dare!",
      default: "Sannu!",
    },
    he: {
      meta: { name: "Hebrew (modern)", nativeName: "עברית" },
      morning: "בוקר טוב!",
      afternoon: "אחר הצהריים טובים!",
      evening: "ערב טוב!",
      night: "לילה טוב!",
      default: "שלום!",
    },
    hz: { meta: { name: "Herero", nativeName: "Otjiherero" } },
    hi: {
      meta: { name: "Hindi", nativeName: "हिन्दी, हिंदी" },
      morning: "शुभ प्रभात!",
      afternoon: "नमस्कार!",
      evening: "सुसंध्या!",
      night: "शुभ रात्रि!",
      default: "हैलो!",
    },
    ho: { meta: { name: "Hiri Motu", nativeName: "Hiri Motu" } },
    hu: {
      meta: { name: "Hungarian", nativeName: "Magyar" },
      morning: "Jó reggelt kívánok!",
      afternoon: "Jó napot!",
      evening: "Jó estét!",
      night: "Jó éjszakát!",
      default: "Szia!",
    },
    ia: { meta: { name: "Interlingua", nativeName: "Interlingua" } },
    id: {
      meta: { name: "Indonesian", nativeName: "Bahasa Indonesia" },
      morning: "Selamat pagi!",
      afternoon: "Selamat sore!",
      evening: "Selamat malam!",
      night: "Selamat malam!",
      default: "Halo!",
    },
    ie: {
      meta: {
        name: "Interlingue",
        nativeName: "Originally called Occidental; then Interlingue after WWII",
      },
    },
    ga: {
      meta: { name: "Irish", nativeName: "Gaeilge" },
      morning: "Maidin mhaith!",
      afternoon: "Tráthnóna maith!",
      evening: "Tráthnóna maith!",
      night: "Oíche mhaith!",
      default: "Dia dhuit!",
    },
    ig: {
      meta: { name: "Igbo", nativeName: "Asụsụ Igbo" },
      morning: "Ụtụtụ ọma!",
      afternoon: "Ehihie ọma!",
      evening: "Mgbede ọma!",
      night: "Ka chifoo!",
      default: "Nnọọ!",
    },
    ik: { meta: { name: "Inupiaq", nativeName: "Iñupiaq, Iñupiatun" } },
    io: { meta: { name: "Ido", nativeName: "Ido" } },
    is: {
      meta: { name: "Icelandic", nativeName: "Íslenska" },
      morning: "Góðan daginn!",
      afternoon: "Góðan daginn!",
      evening: "Gott kvöld!",
      night: "Góða nótt!",
      default: "Halló!",
    },
    it: {
      meta: { name: "Italian", nativeName: "Italiano" },
      morning: "Buongiorno!",
      afternoon: "Buon pomeriggio!",
      evening: "Buonasera!",
      night: "Buona notte!",
      default: "Ciao!",
    },
    iu: { meta: { name: "Inuktitut", nativeName: "ᐃᓄᒃᑎᑐᑦ" } },
    ja: {
      meta: {
        name: "Japanese",
        nativeName: "日本語 (にほんご／にっぽんご)",
      },
      morning: "おはようございます！",
      afternoon: "こんにちは！",
      evening: "こんばんは！",
      night: "おやすみ！",
      default: "こんにちは！",
    },
    jv: { meta: { name: "Javanese", nativeName: "basa Jawa" } },
    kl: {
      meta: {
        name: "Kalaallisut, Greenlandic",
        nativeName: "kalaallisut, kalaallit oqaasii",
      },
    },
    kn: {
      meta: { name: "Kannada", nativeName: "ಕನ್ನಡ" },
      morning: "ಶುಭೋದಯ!",
      afternoon: "ಶುಭ ಅಪರಾಹ್ನ!",
      evening: "ಶುಭ ಸಂಜೆ!",
      night: "ಶುಭ ರಾತ್ರಿ!",
      default: "ಹಲೋ!",
    },
    kr: { meta: { name: "Kanuri", nativeName: "Kanuri" } },
    ks: {
      meta: { name: "Kashmiri", nativeName: "कश्मीरी, كشميري\u200e" },
    },
    kk: {
      meta: { name: "Kazakh", nativeName: "Қазақ тілі" },
      morning: "Қайырлы таң!",
      afternoon: "Қайырлы күн!",
      evening: "Қайырлы кеш!",
      night: "Қайырлы түн!",
      default: "Сәлеметсіз бе!",
    },
    km: {
      meta: { name: "Khmer", nativeName: "ភាសាខ្មែរ" },
      morning: "អរុណ\u200bសួស្តី!",
      afternoon: "សួស្តី!",
      evening: "អរុណសួស្តី!",
      night: "រាត្រី\u200bសួស្តី!",
      default: "សួស្តី!",
    },
    ki: { meta: { name: "Kikuyu, Gikuyu", nativeName: "Gĩkũyũ" } },
    rw: { meta: { name: "Kinyarwanda", nativeName: "Ikinyarwanda" } },
    ky: {
      meta: { name: "Kirghiz, Kyrgyz", nativeName: "кыргыз тили" },
      morning: "Куттуу таң!",
      afternoon: "Куттуу күн!",
      evening: "Куттуу кеч!",
      night: "Куттуу түн!",
      default: "Салам!",
    },
    kv: { meta: { name: "Komi", nativeName: "коми кыв" } },
    kg: { meta: { name: "Kongo", nativeName: "KiKongo" } },
    ko: {
      meta: {
        name: "Korean",
        nativeName: "한국어 (韓國語), 조선말 (朝鮮語)",
      },
      morning: "좋은 아침!",
      afternoon: "안녕하세요!",
      evening: "안녕하세요!",
      night: "안녕히 주무세요!",
      default: "여보세요!",
    },
    ku: {
      meta: { name: "Kurdish", nativeName: "Kurdî, كوردی\u200e" },
      morning: "Beyanî baş!",
      afternoon: "Roj baş!",
      evening: "Êvar baş!",
      night: "Şev baş!",
      default: "Slav!",
    },
    kj: { meta: { name: "Kwanyama, Kuanyama", nativeName: "Kuanyama" } },
    la: {
      meta: { name: "Latin", nativeName: "latine, lingua latina" },
      morning: "Bonum mane!",
      afternoon: "Bona dies!",
      evening: "Bonum vesperam!",
      night: "Bonum nocte",
      default: "Salve!",
    },
    lb: {
      meta: {
        name: "Luxembourgish, Letzeburgesch",
        nativeName: "Lëtzebuergesch",
      },
      morning: "Gudde Moien!",
      afternoon: "Gudden Nomëtteg!",
      evening: "Gudden Owend!",
      night: "Gutt Nuecht!",
      default: "Hallo!",
    },
    lg: { meta: { name: "Luganda", nativeName: "Luganda" } },
    li: {
      meta: {
        name: "Limburgish, Limburgan, Limburger",
        nativeName: "Limburgs",
      },
    },
    ln: { meta: { name: "Lingala", nativeName: "Lingála" } },
    lo: {
      meta: { name: "Lao", nativeName: "ພາສາລາວ" },
      morning: "ສະ\u200bບາຍ\u200bດີ\u200bຕອນ\u200bເຊົ້າ!",
      afternoon: "ສະ\u200bບາຍ\u200bດີ\u200bຕອນ\u200bສວາຍ!",
      evening: "ສະ\u200bບາຍ\u200bດີ\u200bຕອນ\u200bແລງ!",
      night: "ສະບາຍດີ!",
      default: "ສະບາຍດີ!",
    },
    lt: {
      meta: { name: "Lithuanian", nativeName: "lietuvių kalba" },
      morning: "Labas rytas!",
      afternoon: "Laba diena!",
      evening: "Labas vakaras!",
      night: "Labos nakties!",
      default: "Sveiki!",
    },
    lu: { meta: { name: "Luba-Katanga", nativeName: "" } },
    lv: {
      meta: { name: "Latvian", nativeName: "latviešu valoda" },
      morning: "Labrīt!",
      afternoon: "Labdien!",
      evening: "Labvakar!",
      night: "Ar labunakti!",
      default: "Sveiki!",
    },
    gv: { meta: { name: "Manx", nativeName: "Gaelg, Gailck" } },
    mk: {
      meta: { name: "Macedonian", nativeName: "македонски јазик" },
      morning: "Добро утро!",
      afternoon: "Добар ден!",
      evening: "Добро попладне!",
      night: "Добра ноќ!",
      default: "Здраво!",
    },
    mg: {
      meta: { name: "Malagasy", nativeName: "Malagasy fiteny" },
      morning: "Salama!",
      afternoon: "Salama!",
      evening: "Salama!",
      night: "Tafandria mandry!",
      default: "Salama!",
    },
    ms: {
      meta: {
        name: "Malay",
        nativeName: "bahasa Melayu, بهاس ملايو\u200e",
      },
      morning: "Selamat Pagi!",
      afternoon: "Selamat petang!",
      evening: "Selamat petang!",
      night: "Selamat Malam!",
      default: "Helo!",
    },
    ml: {
      meta: { name: "Malayalam", nativeName: "മലയാളം" },
      morning: "സുപ്രഭാതം!",
      afternoon: "ഗുഡ് ആഫ്റ്റർനൂൺ!",
      evening: "ഗുഡ് ഈവനിംഗ്!",
      night: "ശുഭ രാത്രി!",
      default: "ഹലോ!",
    },
    mt: {
      meta: { name: "Maltese", nativeName: "Malti" },
      morning: "Bongu!",
      afternoon: "Il-waranofsinhar it-tajjeb!",
      evening: "Serata tajba!",
      night: "Il-lejl it-tajjeb!",
      default: "Bongu!",
    },
    mi: {
      meta: { name: "Māori", nativeName: "te reo Māori" },
      morning: "Morena koutou!",
      afternoon: "Pai ahiahi!",
      evening: "Āta ahiahi!",
      night: "Pai po!",
      default: "Kia ora!",
    },
    mr: {
      meta: { name: "Marathi (Marāṭhī)", nativeName: "मराठी" },
      morning: "शुभ प्रभात!",
      afternoon: "शुभ दुपार!",
      evening: "शुभ संध्या!",
      night: "शुभ रात्री!",
      default: "नमस्कार!",
    },
    mh: { meta: { name: "Marshallese", nativeName: "Kajin M̧ajeļ" } },
    mn: {
      meta: { name: "Mongolian", nativeName: "монгол" },
      morning: "Өглөөний мэнд!",
      afternoon: "Өдрийн мэнд!",
      evening: "Оройн мэнд!",
      night: "Сайхан амраарай!",
      default: "Сайн уу?",
    },
    na: { meta: { name: "Nauru", nativeName: "Ekakairũ Naoero" } },
    nv: {
      meta: {
        name: "Navajo, Navaho",
        nativeName: "Diné bizaad, Dinékʼehǰí",
      },
    },
    nb: {
      meta: { name: "Norwegian Bokmål", nativeName: "Norsk bokmål" },
    },
    nd: { meta: { name: "North Ndebele", nativeName: "isiNdebele" } },
    ne: {
      meta: { name: "Nepali", nativeName: "नेपाली" },
      morning: "शुभ - प्रभात!",
      afternoon: "शुभ दिउँसो!",
      evening: "शुभ सन्ध्या!",
      night: "शुभ रात्री!",
      default: "नमस्कार!",
    },
    ng: { meta: { name: "Ndonga", nativeName: "Owambo" } },
    nn: {
      meta: { name: "Norwegian Nynorsk", nativeName: "Norsk nynorsk" },
    },
    no: {
      meta: { name: "Norwegian", nativeName: "Norsk" },
      morning: "God morgen!",
      afternoon: "God ettermiddag!",
      evening: "God kveld!",
      night: "God natt!",
      default: "Hallo!",
    },
    ii: { meta: { name: "Nuosu", nativeName: "ꆈꌠ꒿ Nuosuhxop" } },
    nr: { meta: { name: "South Ndebele", nativeName: "isiNdebele" } },
    oc: { meta: { name: "Occitan", nativeName: "Occitan" } },
    oj: { meta: { name: "Ojibwe, Ojibwa", nativeName: "ᐊᓂᔑᓈᐯᒧᐎᓐ" } },
    cu: {
      meta: {
        name:
          "Old Church Slavonic, Church Slavic, Church Slavonic, Old Bulgarian, Old Slavonic",
        nativeName: "ѩзыкъ словѣньскъ",
      },
    },
    om: { meta: { name: "Oromo", nativeName: "Afaan Oromoo" } },
    or: {
      meta: { name: "Oriya", nativeName: "ଓଡ଼ିଆ" },
      morning: "ଶୁଭ ସକାଳ!",
      afternoon: "ଶୁଭ ଅପରାହ୍ନ!",
      evening: "ଶୁଭ ସନ୍ଧ୍ୟା!",
      night: "ଶୁଭରାତ୍ରୀ!",
      default: "ନମସ୍କାର!",
    },
    os: { meta: { name: "Ossetian, Ossetic", nativeName: "ирон æвзаг" } },
    pa: {
      meta: {
        name: "Panjabi, Punjabi",
        nativeName: "ਪੰਜਾਬੀ, پنجابی\u200e",
      },
      morning: "ਸ਼ੁਭ ਸਵੇਰ!",
      afternoon: "ਸਤ ਸ੍ਰੀ ਅਕਾਲ!",
      evening: "ਸਤ ਸ੍ਰੀ ਅਕਾਲ!",
      night: "ਸ਼ੁਭ ਰਾਤ!",
      default: "ਸਤ ਸ੍ਰੀ ਅਕਾਲ!",
    },
    pi: { meta: { name: "Pāli", nativeName: "पाऴि" } },
    fa: {
      meta: { name: "Persian", nativeName: "فارسی" },
      morning: "صبح بخیر!",
      afternoon: "عصر بخیر!",
      evening: "عصر بخیر!",
      night: "شب بخیر!",
      default: "سلام!",
    },
    pl: {
      meta: { name: "Polish", nativeName: "polski" },
      morning: "Dzień dobry!",
      afternoon: "Dzień dobry!",
      evening: "Dobry wieczór!",
      night: "Dobranoc!",
      default: "Witaj!",
    },
    ps: {
      meta: { name: "Pashto, Pushto", nativeName: "پښتو" },
      morning: "سهار مو پخير!",
      afternoon: "ماسپېښين مو نېکمرغه!",
      evening: "ماښام په خیر!",
      night: "ښه شپه!",
      default: "سلام!",
    },
    pt: {
      meta: { name: "Portuguese", nativeName: "Português" },
      morning: "Bom Dia!",
      afternoon: "Boa tarde!",
      evening: "Boa noite!",
      night: "Boa noite!",
      default: "Olá!",
    },
    qu: { meta: { name: "Quechua", nativeName: "Runa Simi, Kichwa" } },
    rm: { meta: { name: "Romansh", nativeName: "rumantsch grischun" } },
    rn: { meta: { name: "Kirundi", nativeName: "kiRundi" } },
    ro: {
      meta: { name: "Romanian, Moldavian, Moldovan", nativeName: "română" },
      morning: "Buna dimineata!",
      afternoon: "Buna ziua!",
      evening: "Bună seara!",
      night: "Noapte bună!",
      default: "Buna!",
    },
    ru: {
      meta: { name: "Russian", nativeName: "русский язык" },
      morning: "Доброе утро!",
      afternoon: "Добрый день!",
      evening: "Добрый вечер!",
      night: "Спокойной ночи!",
      default: "Здравствуйте!",
    },
    sa: {
      meta: { name: "Sanskrit (Saṁskṛta)", nativeName: "संस्कृतम्" },
    },
    sc: { meta: { name: "Sardinian", nativeName: "sardu" } },
    sd: {
      meta: { name: "Sindhi", nativeName: "सिन्धी, سنڌي، سندھی\u200e" },
      morning: "صبح جو سلام!",
      afternoon: "منجهند جو سلام!",
      evening: "شام جو سلام!",
      night: "رات جو سلام!",
      default: "هيلو!",
    },
    se: {
      meta: { name: "Northern Sami", nativeName: "Davvisámegiella" },
    },
    sm: {
      meta: { name: "Samoan", nativeName: "gagana faa Samoa" },
      morning: "Oa mai le ataeao!",
      afternoon: "Oa mai le aoauli!",
      evening: "Oa mai le afiafi!",
      night: "Manuia le po!",
      default: "Talofa!",
    },
    sg: { meta: { name: "Sango", nativeName: "yângâ tî sängö" } },
    sr: {
      meta: { name: "Serbian", nativeName: "српски језик" },
      morning: "Добро јутро!",
      afternoon: "Добар дан!",
      evening: "Добро вече!",
      night: "Лаку ноћ!",
      default: "Здраво!",
    },
    gd: {
      meta: { name: "Scottish Gaelic; Gaelic", nativeName: "Gàidhlig" },
      morning: "Madainn mhath!",
      afternoon: "Feasgar math!",
      evening: "Feasgar math!",
      night: "Oidhche mhath!",
      default: "Halò!",
    },
    sn: {
      meta: { name: "Shona", nativeName: "chiShona" },
      morning: "Mangwanani akanaka!",
      afternoon: "Masikati akanaka!",
      evening: "Manheru akanaka!",
      night: "Manheru akanaka!",
      default: "Mhoro!",
    },
    si: {
      meta: { name: "Sinhala, Sinhalese", nativeName: "සිංහල" },
      morning: "සුභ උදෑසනක්!",
      afternoon: "සුභ සන්ධ්යාවක්!",
      evening: "සුබ සැන්දෑවක්!",
      night: "සුභ රාත්රියක්!",
      default: "හෙලෝ!",
    },
    sk: {
      meta: { name: "Slovak", nativeName: "slovenčina" },
      morning: "Dobré ráno!",
      afternoon: "Dobrý deň!",
      evening: "Dobrý večer!",
      night: "Dobrú noc!",
      default: "Ahoj!",
    },
    sl: {
      meta: { name: "Slovene", nativeName: "slovenščina" },
      morning: "Dobro jutro!",
      afternoon: "Dober večer!",
      evening: "Dober večer!",
      night: "Lahko noč!",
      default: "Zdravo!",
    },
    so: {
      meta: { name: "Somali", nativeName: "Soomaaliga, af Soomaali" },
      morning: "Subax wanaagsan!",
      afternoon: "Galab wanaagsan!",
      evening: "Fiid wanaagsan!",
      night: "Habeen wanaagsan!",
      default: "Salaan!",
    },
    st: {
      meta: { name: "Southern Sotho", nativeName: "Sesotho" },
      morning: "Khotsong!",
      afternoon: "Lumelang!",
      evening: "Lumelang!",
      night: "Robala hantle!",
      default: "Lumela!",
    },
    es: {
      meta: {
        name: "Spanish; Castilian",
        nativeName: "español, castellano",
      },
      morning: "¡Buenos días!",
      afternoon: "¡Buenas tardes!",
      evening: "¡Buena noches!",
      night: "¡Buenas noches!",
      default: "¡Hola!",
    },
    su: {
      meta: { name: "Sundanese", nativeName: "Basa Sunda" },
      morning: "Wilujeng énjing!",
      afternoon: "Wilujeng sonten!",
      evening: "Wilujeng sonten!",
      night: "Wilujeng wengi!",
      default: "Halo!",
    },
    sw: {
      meta: { name: "Swahili", nativeName: "Kiswahili" },
      morning: "Habari za asubuhi!",
      afternoon: "Mchana mzuri!",
      evening: "Habari za jioni!",
      night: "Usiku mwema!",
      default: "Habari!",
    },
    ss: { meta: { name: "Swati", nativeName: "SiSwati" } },
    sv: {
      meta: { name: "Swedish", nativeName: "svenska" },
      morning: "God morgon!",
      afternoon: "God eftermiddag!",
      evening: "God kväll!",
      night: "Godnatt!",
      default: "Hallå!",
    },
    ta: {
      meta: { name: "Tamil", nativeName: "தமிழ்" },
      morning: "காலை வணக்கம்!",
      afternoon: "மதிய வணக்கம்!",
      evening: "மாலை வணக்கம்!",
      night: "இனிய இரவு!",
      default: "வணக்கம்!",
    },
    te: {
      meta: { name: "Telugu", nativeName: "తెలుగు" },
      morning: "శుభోదయం!",
      afternoon: "శుభ మద్యాహ్నం!",
      evening: "శుభ సాయంత్రం!",
      night: "శుభ రాత్రి!",
      default: "హలో!",
    },
    tg: {
      meta: { name: "Tajik", nativeName: "тоҷикӣ, toğikī, تاجیکی\u200e" },
      morning: "Субҳ ба хайр!",
      afternoon: "Нимирӯзи ба хайр!",
      evening: "Шаб ба хайр!",
      night: "Шаби хуш!",
      default: "Салом!",
    },
    th: {
      meta: { name: "Thai", nativeName: "ไทย" },
      morning: "สวัสดีตอนเช้า!",
      afternoon: "สวัสดีตอนบ่าย!",
      evening: "สวัสดีตอนเย็น!",
      night: "ราตรีสวัสดิ์!",
      default: "สวัสดี!",
    },
    ti: { meta: { name: "Tigrinya", nativeName: "ትግርኛ" } },
    bo: {
      meta: {
        name: "Tibetan Standard, Tibetan, Central",
        nativeName: "བོད་ཡིག",
      },
    },
    tk: { meta: { name: "Turkmen", nativeName: "Türkmen, Түркмен" } },
    tl: {
      meta: { name: "Tagalog", nativeName: "Wikang Tagalog, ᜏᜒᜃᜅ᜔ ᜆᜄᜎᜓᜄ᜔" },
      morning: "Magandang umaga!",
      afternoon: "Magandang hapon!",
      evening: "Magandang gabi!",
      night: "Magandang gabi!",
      default: "Kamusta!",
    },
    tn: { meta: { name: "Tswana", nativeName: "Setswana" } },
    to: {
      meta: { name: "Tonga (Tonga Islands)", nativeName: "faka Tonga" },
    },
    tr: {
      meta: { name: "Turkish", nativeName: "Türkçe" },
      morning: "Günaydın!",
      afternoon: "Tünaydın!",
      evening: "İyi akşamlar!",
      night: "İyi geceler!",
      default: "Merhaba!",
    },
    ts: { meta: { name: "Tsonga", nativeName: "Xitsonga" } },
    tt: {
      meta: { name: "Tatar", nativeName: "татарча, tatarça, تاتارچا\u200e" },
    },
    tw: { meta: { name: "Twi", nativeName: "Twi" } },
    ty: { meta: { name: "Tahitian", nativeName: "Reo Tahiti" } },
    ug: {
      meta: {
        name: "Uighur, Uyghur",
        nativeName: "Uyƣurqə, ئۇيغۇرچە\u200e",
      },
      morning: "خەيرلىك ئەتىگەن!",
      afternoon: "خەيرلىك چۈشتىن كېيىن!",
      evening: "خەيرلىك كەچ!",
      night: "خەيرلىك كەچ!",
      default: "ياخشىمۇسىز!",
    },
    uk: {
      meta: { name: "Ukrainian", nativeName: "українська" },
      morning: "Добрий ранок!",
      evening: "Доброго вечора!",
      night: "Надобраніч!",
      default: "Привіт!",
    },
    ur: {
      meta: { name: "Urdu", nativeName: "اردو" },
      morning: "صبح بخیر!",
      afternoon: "شب بخیر!",
      evening: "شام بخیر!",
      night: "شب بخیر!",
      default: "ہیلو!",
    },
    uz: {
      meta: { name: "Uzbek", nativeName: "zbek, Ўзбек, أۇزبېك\u200e" },
      morning: "Xayrli tong!",
      afternoon: "Xayrli kun!",
      evening: "Hayrli kech!",
      night: "Xayrli tun!",
      default: "Salom!",
    },
    ve: { meta: { name: "Venda", nativeName: "Tshivenḓa" } },
    vi: {
      meta: { name: "Vietnamese", nativeName: "Tiếng Việt" },
      morning: "Buổi sáng tốt lành!",
      evening: "Chào buổi tối!",
      night: "Chúc ngủ ngon!",
      default: "Xin chào!",
    },
    vo: { meta: { name: "Volapük", nativeName: "Volapük" } },
    wa: { meta: { name: "Walloon", nativeName: "Walon" } },
    cy: {
      meta: { name: "Welsh", nativeName: "Cymraeg" },
      morning: "Bore da!",
      afternoon: "Prynhawn Da!",
      evening: "Noswaith dda!",
    },
    wo: { meta: { name: "Wolof", nativeName: "Wollof" } },
    fy: {
      meta: { name: "Western Frisian", nativeName: "Frysk" },
      morning: "Goeie moarn!",
      afternoon: "Goeie middei!",
      evening: "Goejûn!",
      night: "Lekker sliepe!",
    },
    xh: { meta: { name: "Xhosa", nativeName: "isiXhosa" } },
    yi: {
      meta: { name: "Yiddish", nativeName: "ייִדיש" },
      afternoon: "א גוטן מיטאג!",
      evening: "גוטן אווענט!",
      night: "א גוטע נאכט!",
    },
    yo: {
      meta: { name: "Yoruba", nativeName: "Yorùbá" },
      default: "Pẹlẹ o!",
    },
    za: {
      meta: { name: "Zhuang, Chuang", nativeName: "Saɯ cueŋƅ, Saw cuengh" },
    },
  };

  var userLang = navigator.language || navigator.userLanguage;
  userLang = userLang.substring(0, 2);

  var userGreetings = greetingsLanguage[userLang] || greetingsLanguage["en"];

  if (hour < 12) {
    return userGreetings.morning;
  } else if (hour < 17) {
    return userGreetings.afternoon;
  } else if (hour < 20) {
    return userGreetings.evening;
  } else if (hour < 24) {
    return userGreetings.night;
  }

  return userGreetings.default;
}

document.getElementById("greeting").innerHTML = getGreeting(
  new Date().getHours()
);
